name = "generative-ai-with-langchain"
version = "0.1.0"
description = "Build large language model (LLM) apps with Python, ChatGPT and other models.."
authors = [
    "Ben Auffarth <auffarth@gmail.com>",
]
readme = "README.md"
repository = "https://github.com/benman1/generative_ai_with_langchain"
keywords = ["llms", "langchain", "ai", "chatgpt", "gpt", "openai", "huggingface"]

[tool.poetry.dependencies]
jupyter>=1.0.0
langchain==0.0.229
huggingface_hub
openai
google-cloud-aiplatform>=1.26.0
replicate
